=== 0rient/paparazzi/conf/abi.dtd
<!ELEMENT abi (messages,async)>
<!ATTLIST abi>

<!ELEMENT messages (message*)>
<!ATTLIST messages>

<!ELEMENT message (field*)>
<!ATTLIST message
  name CDATA #REQUIRED
>

<!ELEMENT field EMPTY>
<!ATTLIST field
  name CDATA #REQUIRED
  type CDATA #REQUIRED
  unit CDATA #IMPLIED
>

<!ELEMENT async (raise*)>
<!ATTLIST async>

<!ELEMENT raise EMPTY>
<!ATTLIST raise
  name CDATA #REQUIRED
  cond CDATA #IMPLIED
>

=== 0rient/paparazzi/conf/abi.xml
<?xml version="1.0"?>
<!DOCTYPE abi SYSTEM "abi.dtd">
<abi>

  <messages>

    <message name="BARO_ABS">
      <field name="pressure" type="float" unit="Pa"/>
    </message>

    <message name="BARO_DIFF">
      <field name="pressure" type="float" unit="Pa"/>
    </message>

    <message name="GPS">
      <field name="gps" type="struct GpsState"/>
    </message>

  </messages>

  <async>
    <raise name="MCU_PERIPH"/>
  </async>

</abi>
